---
- name: Delete RDS instance
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "eu-north-1"
    rds_id: "test-encrypted-db"

  tasks:
    - name: Delete RDS DB instance
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ rds_id }}"
        region: "{{ aws_region }}"
        state: absent
      register: rds_result
    - name: Print RDS deployment results
      debug:
        var: rds_result
