---
- name: Create RDS instance with database
  vars:
    rds_id: "test-encrypted-db"
    rds_engine: "postgres"
    rds_engine_version: "14.6"
    rds_db_instance_class: "db.t3.micro"
    rds_allocated_storage: 5
    rds_db_name: "crda"
    rds_security_group: "crda-postgresql"

  tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: vault
    - name: Get default VPC info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "isDefault": "true"
      register: vpc_net_facts
    - name: Set fact for vpc_id
      set_fact:
        vpc_id: "{{ vpc_net_facts.vpcs[0].vpc_id }}"
    - name: Create security group for RDS instance
      amazon.aws.ec2_security_group:
        name: "{{ rds_security_group }}"
        description: "Allow PostgreSQL connection from Internet"
        vpc_id: "{{ vpc_id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 5432
            cidr_ip: 0.0.0.0/0
            rule_desc: "Allow PostgreSQL connection from Internet"
      register: vpc_security_group
    # - name: Print RDS deployment results
    #   debug:
    #     var: vpc_security_group
    - name: Create a DB instance using the default AWS KMS encryption key
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ rds_id }}"
        db_instance_class: "{{ rds_db_instance_class }}"
        db_name: "{{ rds_db_name }}"
        engine: "{{ rds_engine }}"
        master_username: "{{ master_username }}"
        master_user_password: "{{ master_user_password }}"
        region: "{{ aws_region }}"
        multi_az: false
        publicly_accessible: true
        allocated_storage: "{{ rds_allocated_storage }}"
        storage_encrypted: true
        storage_type: gp2
        state: present
        deletion_protection: true
        vpc_security_group_ids:
          - "{{ vpc_security_group.group_id }}"
      register: rds_result
    - name: Print RDS deployment results
      debug:
        var: rds_result.endpoint.address
